FROM arm32v7/python:3.5-jessie

# Set the working directory to /app
WORKDIR /app

MAINTAINER Daniel Kampert <danielkampert@kampis-elektroecke.de>

# Copy the current directory contents into the container at /app
ADD . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Run app.py when the container launches
CMD ["python", "app.py"]
